# Generated by Django 3.1.5 on 2021-01-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routcalc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='daliveryTime',
        ),
        migrations.AddField(
            model_name='route',
            name='deliveryTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='deliveryDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
